version: '3.5'

services:
    openjdk:
        build:
            args:
                CONTAINER_NAME: openjre_8u131.11-r2
                CONTAINER_VERSION: 1.0.7
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180325
            cache_from:
                - base_container:20180325
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        image: openjre_8u131.11-r2:20180325 
