version: '3.5'

services:
    openjdk:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: openjre_8u131.11-r2
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:latest
            cache_from:
                - base_container:latest
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: openjre_8u131.11-r2:latest 
