version: '3.5'

services:
    openjdk:
        build:
            args:
                CONTAINER_VERSION: 1.0.2
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180217
            cache_from:
                - base_container:20180217
                - alpine:3.6                 
            context: .
        image: openjre_8u131.11-r2:20180217 

    base:
        build:
            args:
                DEBUG_TRACE: 0
                CONTAINER_VERSION: 1.0.2
                FROM_BASE: alpine:3.6
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ../base_container
        image: base_container:20180217
