version: '3.5'

services:
    openjdk:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: openjre_8u131.11-r2
<<<<<<< HEAD
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:latest
            cache_from:
                - base_container:latest
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: openjre_8u131.11-r2:latest 
=======
                CONTAINER_VERSION: 1.0.7
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180325
            cache_from:
                - base_container:20180325
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        image: openjre_8u131.11-r2:20180325 
>>>>>>> master
