version: '3.3'

services:
    openjre8:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: openjre8
                FROM_BASE: ${DOCKER_REGISTRY:-}base_container:${CONTAINER_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}base_container:${CONTAINER_TAG:-latest}
            context: .
        container_name: openjre8
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: ${DOCKER_REGISTRY:-}openjre8:${CONTAINER_TAG:-latest}
        labels:
            container.fingerprint: $CONTAINER_FINGERPRINT
            container.git.branch: $CONTAINER_GIT_BRANCH
            container.git.commit: $CONTAINER_GIT_COMMIT
            container.git.url: $CONTAINER_GIT_URL
            container.origin: $CONTAINER_ORIGIN
            container.original.name: openjre8
            container.version: ${CONTAINER_VERSION:-3.0.0}
