version: '3.3'

services:
    openjre8:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: openjre_8u131.11-r2
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: base_container:${CONTAINER_TAG:-latest}
            cache_from:
                - base_container:${CONTAINER_TAG:-latest}
                - alpine:3.8
            context: .
        container_name: openjre8
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: openjre_8u131.11-r2:${CONTAINER_TAG:-latest} 
