version: '3.5'

services:
    openjdk:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
                - alpine:3.6                 
            context: .
        depends_on:
            - base
        image: openjre_8u131.11-r2:20180210 

    base:
        build:
            args:
                CODE_VERSION: alpine:3.6
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ../base_container
        image: base_container:20180210
