version: '3.3'

services:
    openjre:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: openjre
                FROM_BASE: ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}base_container:${BASE_TAG:-latest}
                JAVA_VERSION: ${JAVA_VERSION:-8.171.11-r0}
            cache_from:
                - ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.cbf.version: $CBF_VERSION
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: openjre
        container_name: openjre
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}openjre/${JAVA_VERSION:-8.171.11-r0}:${CONTAINER_TAG:-latest}
