version: '3.5'

services:
    openjdk:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
                - alpine:3.6                 
            context: .
#        depends_on:
#            - base_container:20180210
        image: openjre_8u131.11-r2:20180210 
