version: '3.3'

# repo: https://github/ballab1/openjre.git
# containerOS: alpine

services:
    openjre:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: openjre
                FROM_BASE: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                JAVA_VERSION: ${JAVA_VERSION:-.11.0.9_p11-r0}
                JAVA_EXTENDED: ${JAVA_EXTENDED:-8.181.13-r0}
                JAVA_PACKAGE: ${JAVA_PACKAGE:-1.8.0-openjdk }
            cache_from:
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.12.4}
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: openjre
                container.parent: $CONTAINER_PARENT
                version.cbf: $CBF_VERSION
        container_name: openjre
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/openjre/${JAVA_VERSION:-.11.0.9_p11-r0}:${CONTAINER_TAG:-latest}
