version: '3.5'

services:
    openjdk:
        build:
            args:
                CONTAINER_VERSION: 1.0.2
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180217
            cache_from:
                - base_container:20180217
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        environment:
            CONTAINER_NAME: openjre_8u131.11-r2
        image: openjre_8u131.11-r2:20180217 
